/* Generated by Yosys 0.68+40 (git sha1 0f2bcb94b-dirty, Release, GNU /usr/bin/x86_64-w64-mingw32-g++ 15.2.1) */

(* top =  1  *)
(* src = "dff.v:1.1-11.10" *)
module dff(q, data, clk, rst);
  reg \$auto$verilog_backend.cc:2505:dump_module$2  = 0;
  (* src = "dff.v:2.12-2.13" *)
  output q;
  reg q;
  (* src = "dff.v:3.7-3.11" *)
  input data;
  wire data;
  (* src = "dff.v:3.12-3.15" *)
  input clk;
  wire clk;
  (* src = "dff.v:3.16-3.19" *)
  input rst;
  wire rst;
  (* src = "dff.v:4.1-10.4" *)
  reg _0_;
  always @* begin
    if (\$auto$verilog_backend.cc:2505:dump_module$2 ) begin end
    _0_ = q;
    (* src = "dff.v:6.5-9.10" *)
    if (rst) begin
      _0_ = 1'h0;
    end else begin
      _0_ = data;
    end
  end
  always @(posedge clk) begin
      q <= _0_;
  end
  always @(posedge rst) begin
      q <= _0_;
  end
endmodule
