/* Generated by Yosys 0.68+40 (git sha1 0f2bcb94b-dirty, Release, GNU /usr/bin/x86_64-w64-mingw32-g++ 15.2.1) */

(* top =  1  *)
(* src = "xnor_gate.v:1.1-5.10" *)
module xnor_gate(y, a, b);
  (* src = "xnor_gate.v:2.8-2.9" *)
  output y;
  wire y;
  (* src = "xnor_gate.v:3.7-3.8" *)
  input a;
  wire a;
  (* src = "xnor_gate.v:3.9-3.10" *)
  input b;
  wire b;
  (* src = "xnor_gate.v:4.14-4.19" *)
  wire _0_;
  assign _0_ = a ^(* src = "xnor_gate.v:4.14-4.19" *)  b;
  assign y = ~(* src = "xnor_gate.v:4.12-4.20" *) _0_;
endmodule
