/* Generated by Yosys 0.68+40 (git sha1 0f2bcb94b-dirty, Release, GNU /usr/bin/x86_64-w64-mingw32-g++ 15.2.1) */

(* top =  1  *)
(* src = "nand_gate.v:1.1-5.10" *)
module nand_gate(y, a, b);
  (* src = "nand_gate.v:2.8-2.9" *)
  output y;
  wire y;
  (* src = "nand_gate.v:3.7-3.8" *)
  input a;
  wire a;
  (* src = "nand_gate.v:3.9-3.10" *)
  input b;
  wire b;
  (* src = "nand_gate.v:4.12-4.15" *)
  wire _0_;
  assign _0_ = a &(* src = "nand_gate.v:4.12-4.15" *)  b;
  assign y = ~(* src = "nand_gate.v:4.10-4.16" *) _0_;
endmodule
