/* Generated by Yosys 0.68+40 (git sha1 0f2bcb94b-dirty, Release, GNU /usr/bin/x86_64-w64-mingw32-g++ 15.2.1) */

(* top =  1  *)
(* src = "xor_gate.v:1.1-5.10" *)
module xor_gate(y, a, b);
  (* src = "xor_gate.v:2.8-2.9" *)
  output y;
  wire y;
  (* src = "xor_gate.v:3.7-3.8" *)
  input a;
  wire a;
  (* src = "xor_gate.v:3.9-3.10" *)
  input b;
  wire b;
  assign y = a ^(* src = "xor_gate.v:4.12-4.17" *)  b;
endmodule
