/* Generated by Yosys 0.68+40 (git sha1 0f2bcb94b-dirty, Release, GNU /usr/bin/x86_64-w64-mingw32-g++ 15.2.1) */

(* top =  1  *)
(* src = "not_gate.v:1.1-5.10" *)
module not_gate(y, a);
  (* src = "not_gate.v:2.8-2.9" *)
  output y;
  wire y;
  (* src = "not_gate.v:3.7-3.8" *)
  input a;
  wire a;
  (* src = "not_gate.v:4.10-4.12" *)
  wire _0_;
  assign _0_ = ~ (* src = "not_gate.v:4.10-4.12" *) a;
  assign y = _0_;
endmodule
